/* eslint-disable jsx-a11y/alt-text */
/**
 * eslint-disable @next/next/inline-script-id
 *
 * @format
 */

/** @format */

import Image from "next/image";
import styles from "./styles/page.module.css";
import Head from "next/head";
import Script from "next/script";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Hunting Code By Tamim</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="next, javascript, huntingCode, blog" />
        <link rel="rel" href="./favicon.ico" />
      </Head>

 

      <main className={styles.main}>
        <h1 className={styles.title}>Hunting Code By Tamim</h1>

        <div className={styles.imgWrap}>
          <Image
            className={styles.myImg}
            src="/photo-1623282033815-40b05d96c903.avif"
            width={500}
            height={300}
            alt="Photo by Tamim"
          />
        </div>

        <p>A blog for hunting Coders by hunting coder tamim</p>

        <div className="blogSection">
          <h2 className={styles.blogIntro}>Popular Blogs</h2>
          <div className={styles.blogs}>
            <div className={styles.blogItem}>
              <h3>How to Learn javascript in 2022</h3>
              <p>
                Javascript is one of the most popular programming languages in
                the world
              </p>
            </div>

            <div className={styles.blogItem}>
              <h3>How to Learn javascript in 2022</h3>
              <p>
                Javascript is one of the most popular programming languages in
                the world
              </p>
            </div>

            <div className={styles.blogItem}>
              <h3>How to Learn javascript in 2022</h3>
              <p>
                Javascript is one of the most popular programming languages in
                the world
              </p>
            </div>
            
          </div>
        </div>
        
      </main>
    </>
  );
}
